### ISSUE TITLE
some errors. libssl-dev

### ISSUE THREAD

**Issue by brunocasado** [richardjoo/HTMLCOIN#5]
Hi, i'm trying compile on ubuntu 16.04 and i have some issues

first, on ubuntu 16.04  i had to do an downgrade on libssl-dev to 1.0.2g-1ubuntu4.10

Solved this error:

```
key.cpp: In function ‘bool EnsureLowS(std::vector<unsigned char>&)’:
key.cpp:149:19: error: invalid use of incomplete type ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
     if (BN_cmp(sig->s, halforder) > 0) {
                   ^
In file included from /usr/include/openssl/ecdsa.h:10:0,
                 from key.cpp:17:
/usr/include/openssl/ec.h:1039:16: note: forward declaration of ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
 typedef struct ECDSA_SIG_st ECDSA_SIG;
                ^
key.cpp:151:19: error: invalid use of incomplete type ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
         BN_sub(sig->s, order, sig->s);
                   ^
In file included from /usr/include/openssl/ecdsa.h:10:0,
                 from key.cpp:17:
/usr/include/openssl/ec.h:1039:16: note: forward declaration of ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
 typedef struct ECDSA_SIG_st ECDSA_SIG;
                ^
key.cpp:151:34: error: invalid use of incomplete type ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
         BN_sub(sig->s, order, sig->s);
                                  ^
In file included from /usr/include/openssl/ecdsa.h:10:0,
                 from key.cpp:17:
/usr/include/openssl/ec.h:1039:16: note: forward declaration of ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
 typedef struct ECDSA_SIG_st ECDSA_SIG;
                ^
Makefile:7638: recipe for target 'libbitcoin_common_a-key.o' failed
make[2]: *** [libbitcoin_common_a-key.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/home/bruno/HTMLCOIN/src'
Makefile:13692: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/bruno/HTMLCOIN/src'
Makefile:693: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

```

Now i got this error but i cant solve:

```
qt/paymentrequestplus.cpp: In member function ‘bool PaymentRequestPlus::getMerchant(X509_STORE*, QString&) const’:
qt/paymentrequestplus.cpp:163:42: error: ‘EVP_MD_CTX_new’ was not declared in this scope
         EVP_MD_CTX *ctx = EVP_MD_CTX_new();
                                          ^
qt/paymentrequestplus.cpp:178:28: error: ‘EVP_MD_CTX_free’ was not declared in this scope
         EVP_MD_CTX_free(ctx);
                            ^
Makefile:10662: recipe for target 'qt/qt_libbitcoinqt_a-paymentrequestplus.o' failed
make[2]: *** [qt/qt_libbitcoinqt_a-paymentrequestplus.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/home/bruno/HTMLCOIN/src'
Makefile:13692: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/bruno/HTMLCOIN/src'
Makefile:693: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
bruno@bruno-Latitude-3540:~/HTMLCOIN$ make -j2
Making all in src
make[1]: Entering directory '/home/bruno/HTMLCOIN/src'
make[2]: Entering directory '/home/bruno/HTMLCOIN/src'
  CXX      qt/qt_libbitcoinqt_a-paymentrequestplus.o
  CXX      qt/qt_libbitcoinqt_a-receivecoinsdialog.o
qt/paymentrequestplus.cpp: In member function ‘bool PaymentRequestPlus::getMerchant(X509_STORE*, QString&) const’:
qt/paymentrequestplus.cpp:163:42: error: ‘EVP_MD_CTX_new’ was not declared in this scope
         EVP_MD_CTX *ctx = EVP_MD_CTX_new();
                                          ^
qt/paymentrequestplus.cpp:178:28: error: ‘EVP_MD_CTX_free’ was not declared in this scope
         EVP_MD_CTX_free(ctx);
                            ^
Makefile:10662: recipe for target 'qt/qt_libbitcoinqt_a-paymentrequestplus.o' failed
make[2]: *** [qt/qt_libbitcoinqt_a-paymentrequestplus.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/home/bruno/HTMLCOIN/src'
Makefile:13692: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/bruno/HTMLCOIN/src'
Makefile:693: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```

some ideia?

Sorry if i post the question in wrong place.

**Comment by brunocasado** [comment]
well, how can i say.
i kicked and worked :)
in really, all i did was re run  ./autogen and ./configure 

after this, make work without problem.

I think that after downgrade libssl you need start process again.

thanks!
